### ISSUE TITLE
launch_test

### ISSUE THREAD

**Issue by absolutProgrammer** [louisoutin/rat_crypto_trader#3]
works completely incorrect. It has old usage of class DataMatrices 
and after changing it to a normal one (I have taken it from lanch_train and changed to date_start=ctx["test_range"]["start"] and date_end=ctx["test_range"]["end"]).

Now I got an error in rat/network/encoder_decoder.py file:

Traceback (most recent call last):
  File "/rat_crypto_trader_master/rat/main.py", line 202, in <module>
    run_main()
  File "/rat_crypto_trader_master/rat/main.py", line 66, in run_main
    launch_test(ctx)
  File "/rat_crypto_trader_master/rat/main.py", line 181, in launch_test
    tst_portfolio_value, SR, CR, St_v, tst_pc_array, TO = test_net(DM, x_window_size, local_context_length, model,
  File "/rat_crypto_trader_master/rat/test.py", line 15, in test_net
    tst_long_term_w, tst_trg_y = test_online(DM, x_window_size, model,
  File "/rat_crypto_trader_master/rat/test.py", line 61, in test_online
    out = model.forward(tst_src, tst_currt_price, tst_previous_w,
  File "/rat_crypto_trader_master/rat/network/encoder_decoder.py", line 114, in forward
    out = torch.cat([decode_out, previous_w], 2)  # [128,11,2*12]  cat [128,11,1] -> [128,11,2*12+1]
RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 2. Got 1 and 0 in dimension 0 (The offending index is 1)

**Comment by louisoutin** [comment]
6 months I didn't touch that repo, I'm super busy I'll not have time to help you.
However from what I remember, the code was running fine since this last commit.
